# Generated by Django 5.0.2 on 2024-03-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulu", models.CharField(max_length=50)),
                ("deskrisaun", models.CharField(max_length=225)),
            ],
        ),
    ]
