# Generated by Django 5.0.2 on 2024-03-16 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_portfolio_imajen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naran", models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name="portfolio",
            name="enderesu_url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naran", models.CharField(max_length=100)),
                ("data_hahu", models.DateField()),
                ("data_remata", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Inisiu", "Inisiu"),
                            ("Prosesu Hela", "Prosesu Hela"),
                            ("Finalizadu", "Finalizadu"),
                        ],
                        default="Inisiu",
                        max_length=20,
                    ),
                ),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.categoria"
                    ),
                ),
                (
                    "portfolio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="main.portfolio"
                    ),
                ),
            ],
        ),
    ]
