# Generated by Django 5.0.2 on 2024-04-13 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_project_portfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="portfolio",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to="main.portfolio",
            ),
        ),
    ]
