# Generated by Django 5.0.2 on 2024-04-14 01:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
